name: Merge pull request to main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
    print-shas:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true

        steps:
          - name: print shas
            run: |
                echo 'github.event.before $${{ github.event.before }}'
                echo 'github.event.after ${{ github.event.after }}'
                echo 'github.head_ref ${{ github.head_ref }}'
                echo 'github.event.pull_request.head.sha ${{ github.event.pull_request.head.sha }}'
                echo 'github.sha ${{ github.sha }}'
                echo 'github.merge_commit_sha ${{ github.merge_commit_sha }}'
