name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: print shas
        run: |
          echo 'github.event.before $${{ github.event.before }}'
          echo 'github.event.after ${{ github.event.after }}'
          echo 'github.head_ref ${{ github.head_ref }}'
          echo 'github.event.pull_request.head.sha ${{ github.event.pull_request.head.sha }}'
          echo 'github.sha ${{ github.sha }}'
          echo 'github.merge_commit_sha ${{ github.merge_commit_sha }}'

      # - uses: docker/setup-buildx-action@v3

      # - uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - uses: docker/metadata-action@v5
      #   id: meta
      #   with:
      #     images: ${{ env.IMAGE }}

      # - uses: docker/bake-action@v5
      #   id: bake
      #   with:
      #     files: |
      #         ./docker-bake.hcl
      #         ${{ steps.meta.outputs.bake-file }}
      #     push: true
